### PR TITLE
Support tvOS and watchOS

### PR DESCRIPTION
**Pull request by notgull**
This PR adds support for `tvOS` and `watchOS`, using the existing `kqueue` setup.

### CODE REVIEW

**Comment by notgull** [comment]
Whoops, it looks like `libc` doesn't support tvOS yet.

**Comment by taiki-e** [comment]
> it looks like `libc` doesn't support tvOS yet.

Hmm, I thought libc [0.2.136](https://github.com/rust-lang/libc/releases/tag/0.2.136)+ support it.

**Comment by notgull** [comment]
It looks like you're right, I think I was looking at an old libc version.

**Comment by taiki-e** [comment]
Would you update the following docs?
https://github.com/smol-rs/polling/blob/f0afd7788e3f60865be7808dd78a02e55ff75f6c/README.md?plain=1#L16
https://github.com/smol-rs/polling/blob/f0afd7788e3f60865be7808dd78a02e55ff75f6c/src/kqueue.rs#L1

And the following cfgs?
https://github.com/smol-rs/polling/blob/f0afd7788e3f60865be7808dd78a02e55ff75f6c/src/lib.rs#L452-L453
https://github.com/smol-rs/polling/blob/f0afd7788e3f60865be7808dd78a02e55ff75f6c/src/lib.rs#L466-L467
https://github.com/smol-rs/polling/blob/f0afd7788e3f60865be7808dd78a02e55ff75f6c/tests/precision.rs#L29-L30
https://github.com/smol-rs/polling/blob/f0afd7788e3f60865be7808dd78a02e55ff75f6c/tests/precision.rs#L65-L66

**Review by taiki-e — APPROVED** [review]

**Pull request merged**
