### PR TITLE
feat: Expose kqueue's signal handling functionality

### PR DESCRIPTION
**Pull request by notgull**
This PR exposes functions that allow users to register signal handlers using `kqueue`.

See also: #68

### CODE REVIEW

**Comment by notgull** [comment]
I can't reproduce the test failures on FreeBSD. I guess I have to boot up my macOS VM...

**Comment by zseri** [comment]
uhh I can reproduce the test failure on native FreeBSD... truss trace: https://ytrizja.de/misc/other_modes.truss

**Comment by zseri** [comment]
maybe the event needs to be re-enabled?

**Comment by zseri** [comment]
also take note of https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258412

**Comment by notgull** [comment]
Superseded by #83

**Comment by zseri** [comment]
ok, appears to be fixed in the new branch

**Pull request closed without merging**
